version: '3.8'
services:
  app:
    image: aoirint/nalypoll:20230205.1
    restart: always
    volumes:
      - static-data:/static
    env_file:
      - .env.django
    depends_on:
      - db
  updater:
    image: aoirint/nalypoll:20230205.1
    command: bash -c "sleep 1s && python3 tools/PollUpdater.py"
    restart: always
    env_file:
      - .env.django
    depends_on:
      - db
  db:
    image: mariadb:10.4
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.mysql
  nginx:
    image: nginx:1.23
    restart: always
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - static-data:/static
    depends_on:
      - app

volumes:
  db-data:
  static-data:

